In [6]:
import nltk
from nltk.corpus import stopwords
import pathlib

In [4]:
stopwords.words('en')

OSError: No such file or directory: '/Users/oleksandr/nltk_data/corpora/stopwords/en'

In [11]:
for path in pathlib.Path("/Users/oleksandr/nltk_data/corpora/stopwords/").glob("*"):
    print(path.stem, end=" ")

albanian dutch catalan german slovene hinglish hungarian romanian kazakh turkish russian README italian english greek tajik norwegian portuguese hebrew finnish danish french swedish belarusian azerbaijani spanish tamil chinese indonesian arabic nepali ukrainian bengali basque 

In [10]:
mlb.fit_transform([["a", "b", "c", "d", "f"]])

array([[1, 1, 1, 1, 1]])

In [12]:
mlb.transform([["a", "c", "g"]])

/Users/oleksandr/me/repos/university/diploma/.venv/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['g'] will be ignored
  warnings.warn(


array([[1, 0, 1, 0, 0]])

In [12]:
import numpy as np

In [15]:
a1 = np.random.randint(0, 10, (10, 3))
a2 = np.random.randint(0, 10, (10, ))

In [19]:
a1.reshape(a1.shape).shape

(10, 3)

In [21]:
a2.reshape(a2.shape if len(a2.shape) == 2 else (a2.shape[0], 1))

array([[7],
       [0],
       [7],
       [7],
       [5],
       [0],
       [5],
       [5],
       [4],
       [8]])